### ISSUE TITLE
pi3b+ docker error

### ISSUE THREAD

**Issue by thelostinthought** [Home-Is-Where-You-Hang-Your-Hack/sensor.goveetemp_bt_hci#27]
I tried to follow the instructions in the readme.  I'm running on a pi3b+ with docker and homeassistant 0.117.6.  My docker-compose looks like:

 version: "3.8"
 services:
    homeassistant:
       container_name: homeassistant
       image: homeassistant/raspberrypi3-homeassistant:stable
       network_mode: host
       volumes:
          - "./homeassistant/:/config/"

I'm getting an error in homeassistant of:

Logger: homeassistant.components.sensor
Source: custom_components/govee_ble_hci/sensor.py:202
Integration: Sensor (documentation, issues)
First occurred: 11:04:24 AM (1 occurrences)
Last logged: 11:04:24 AM
Error while setting up govee_ble_hci platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/govee_ble_hci/sensor.py", line 202, in setup_platform
    adapter = get_provider().get_adapter(int(config[CONF_HCI_DEVICE][-1]))
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_provider.py", line 11, in get_adapter
    adapter.off()
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 100, in off
    self.send_cmd_value(HCIDEVDOWN, self.device_id)
  File "/usr/local/lib/python3.8/site-packages/bleson/providers/linux/linux_adapter.py", line 47, in send_cmd_value
    fcntl.ioctl(self._socket.fileno(), cmd, value)
PermissionError: [Errno 1] Operation not permitted

I believe this has to do with step1 and setcap which wouldn't work in docker.  Any ideas?

**Comment by Thrilleratplay** [comment]
@thelostinthought You are probably missing `privileged: true` in your docker-compose yaml.  This is usually not an issue on Raspberry PIs because most just use the preconfigured Home Assistant operating system/HASS/whatever it is called these days. which includes supervisor docker orchestration  

Any reason why you are running HA this way?   If you are running other docker containers, be aware that this component uses active Bluetooth scanning and can block other Bluetooth services.

**Comment by thelostinthought** [comment]
I will be a guest container on the system. I can't run privileged.  I'm temporarily running on the pi as proof of concept before being moved over to the main system.  I'm allowed to pass a device, and on the new system I get a dedicated bluetooth dongle.  I tried passing ttyAMA0 & vcio with errors.  I also tried passing the entire usb bus thinking the bluetooth chip might be hiding there.  I might have to wait for a bluetooth dongle to come in the mail before i can do anything else.

**Comment by Thrilleratplay** [comment]
You are a guest container on a RaspberryPi and want to monitor the local temperature?  Unfortunately, due to the permissions of docker, you will either need privileged or possibly be able to pass in `--cap-add=SYS_ADMIN `, both of which would require the same permissions.  Even with an external dongle, docker will not have direct access to hardware by design without additional permissions.  These issues are beyond the scope of this component.
